### ISSUE TITLE
Permission Denied: Failed to fetch user and post

### ISSUE THREAD

**Issue by HelloHaoM** [mac-gallagher/InstagramClone#1]
Hi,

When I try to run the project, it has an error:

`Failed to fetch user from database: Error Domain=com.firebase Code=1 "Permission Denied"`

Could you help me to figure it out?

**Comment by mac-gallagher** [comment]
This is likely because you have not set the security rules for your Firebase Database. 

Navigate to the `Database` tab in your Firebase Console and then to the `Realtime Database`. You should see a tab that says `Rules`. You can then paste in the following code snippet:

```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```
If you are publishing your project on the App Store, you should **absolutely** set more secure rules (the above code allows anyone to read/write to your database). However, this should suffice for temporary development purposes.

**Comment by HelloHaoM** [comment]
It works. Thanks
